name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true
      nextVersion:
        description: 'Next Version (-SNAPSHOT will be added automatically) '
        type: string
        required: true
        
jobs:
  change_version_push_tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.getPreviousVersion.outputs.version }}
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
      with:
        persist-credentials: true
        fetch-depth: 0   
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Get Project Snapshot Version from pom.xml
      uses: entimaniac/read-pom-version-action@1.0.0
      id: getVersion
      
    - name: Print the version
      run: echo "The version we just got is ${{ steps.getVersion.outputs.version }}"
        
    - name: Change values.yaml and pom.xml
      run: |
        # Update values.yaml and Chart.yaml with new tag
        yq -i '.image.tag = "${{ inputs.version }}"' ./helm/values.yaml
        yq -i '.version = "${{ inputs.version }}"' ./helm/Chart.yaml
        # Update pom.xml with new tag
        python -c 'import xml.etree.ElementTree as ET;ET.register_namespace("", "http://maven.apache.org/POM/4.0.0");ctb=ET.TreeBuilder(insert_comments=True);xp=ET.XMLParser(target=ctb);tree=ET.parse("pom.xml", parser=xp);root=tree.getroot();version_element=root.find("{http://maven.apache.org/POM/4.0.0}version").text="${{ inputs.version }}";tree.write("pom.xml",encoding="UTF-8",xml_declaration=True);'

    - name: Commit, push and tag
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -a -m "Release ${{ inputs.version }}"
        git push
        git tag -a v${{ inputs.version }} -m "Release ${{ inputs.version }}."
        git push origin v${{ inputs.version }}

  create_release:
    runs-on: ubuntu-latest
    needs: change_version_push_tag
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
      with:
        persist-credentials: true
        fetch-depth: 0
        
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git fetch && git reset --hard origin/master
        gh release create v${{ inputs.version }}

  call_workflow:
    needs: create_release
    uses: ./.github/workflows/automated_ci.yml
    secrets: inherit
          
  change_next_version_push:
    runs-on: ubuntu-latest
    needs: call_workflow
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
      with:
        persist-credentials: true
        fetch-depth: 0   
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
        
    - name: Change values.yaml and pom.xml
      run: |
        git fetch && git reset --hard origin/master
        # Update values.yaml with new tag
        yq -i '.image.tag = "${{ inputs.nextVersion }}-SNAPSHOT"' ./helm/values.yaml
        yq -i '.version = "${{ inputs.nextVersion }}-SNAPSHOT"' ./helm/Chart.yaml
        # Update pom.xml with new tag
        python -c 'import xml.etree.ElementTree as ET;ET.register_namespace("", "http://maven.apache.org/POM/4.0.0");ctb=ET.TreeBuilder(insert_comments=True);xp=ET.XMLParser(target=ctb);tree=ET.parse("pom.xml", parser=xp);root=tree.getroot();version_element=root.find("{http://maven.apache.org/POM/4.0.0}version").text="${{ inputs.nextVersion }}-SNAPSHOT";tree.write("pom.xml",encoding="UTF-8",xml_declaration=True);'

    - name: Commit, push and tag
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -a -m "Set next version ${{ inputs.nextVersion }}-SNAPSHOT"
        git push
        git tag -a v${{ inputs.nextVersion }}-SNAPSHOT -m "Pre Release ${{ inputs.nextVersion }}-SNAPSHOT."
        git push origin v${{ inputs.nextVersion }}-SNAPSHOT

  pre_release:
    runs-on: ubuntu-latest
    needs: [change_next_version_push, change_version_push_tag]
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
      with:
        persist-credentials: true
        fetch-depth: 0
          
    - name: Pre_Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git fetch && git reset --hard origin/master
        gh release delete v${{needs.change_version_push_tag.outputs.version}}
        gh release create v${{ inputs.nextVersion }}-SNAPSHOT

  call_workflow_new:
    needs: pre_release
    uses: ./.github/workflows/automated_ci.yml
    secrets: inherit
  
        

          
