name: Release.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New Version'
        type: string
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: true
        fetch-depth: 0   
        
    - name: Create local changes
      run: |
        # Update values.yaml with new tag
        yq '.image.tag = ${{ inputs.version }}' ./helm/values.yaml

    - name: Modify an element in XML file
      uses: Mudlet/xmlstarlet-action@master
      id: xml_replace
      with:
        args: ed -O -u "/project/version" -v "${{ inputs.version }}" pom.xml

    - name: Create local changes
      run: |
        cat pom.xml
                
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
