name: Release.

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New Version'
        type: string
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: true
        fetch-depth: 0   
        
    - name: Create local changes
      run: |
        # Update values.yaml with new tag
        yq '.image.tag = ${{ inputs.version }}' ./helm/values.yaml
        
    - name: Set logback env values
      uses: rvolo/xml-replace-action@v0.2
      with:
        filepath: "pom.xml"
        xpath: "/project/version"
        replace: "${{ inputs.version }}"

    - name: Create local changes
      run: |
        cat pom.xml
                
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
